---
# SSH
ssh_public_key_files:
    - ~/.ssh/id_rsa.pub

# -------------------------------
# Firewall Configuration (firewalld)
# -------------------------------

private_network_subnet: "10.0.0.0/16"

whitelisted_ips:
    # Your IP from which you would like to access the cluster
    # Can be a home IP (if you have a fixed IP) or a server on the
    # internet you use for administrating other machines
    - "85.25.235.187/32"

open_services:
    - ssh
    - http
    - https

# -------------------------------
# Admin email notifications
# -------------------------------

admin_email: andromeda--k8s-cluster@nostran.com
notifications_email: soltesz.andras@gmail.com


# -------------------------------
# Fail2Ban configuration
# -------------------------------

#fail2ban_services:
#    - name: ssh

# Fail2ban
fail2ban_sender: andromeda-k8s-cluster@nostran.com

fail2ban_ignoreips:
    # See whitelisted IPs
    - 85.25.235.187

fail2ban_destemail: soltesz.andras@gmail.com

